# SAM configuration file for MonitorTradesLambda
# This file contains default configuration values for the SAM CLI

version = 0.1

[default]
[default.global.parameters]
stack_name = "monitor-trades-lambda"
s3_bucket = "your-sam-bucket-name"
s3_prefix = "monitor-trades-lambda"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AlpacaSecretName=trading/alpaca/credentials"
image_repositories = []

[default.build.parameters]
cached = true
parallel = true


