AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Initiate Exit Trades Lambda Function

Parameters:
  AlpacaSecretName:
    Type: String
    Description: Name of the AWS Secrets Manager secret containing Alpaca API credentials
    Default: alpaca-trading-credentials
  
  PaperTrading:
    Type: String
    Description: Whether to use paper trading (true) or live trading (false)
    Default: 'true'
    AllowedValues: ['true', 'false']
  
  Environment:
    Type: String
    Description: Environment name
    Default: dev
    AllowedValues: ['dev', 'staging', 'prod']

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: java11
    Environment:
      Variables:
        ALPACA_SECRET_NAME: !Ref AlpacaSecretName
        PAPER_TRADING: !Ref PaperTrading
        AWS_REGION: !Ref AWS::Region

Resources:
  InitiateExitTradesLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Environment}-initiate-exit-trades-lambda'
      CodeUri: target/initiate-exit-trades-lambda-1.0.0.jar
      Handler: com.trading.lambda.InitiateExitTradesLambda::handleRequest
      Description: Lambda function for exiting multi-leg option positions
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${AlpacaSecretName}*'
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(45 14 ? * MON-FRI *)  # 9:45 AM EST (2:45 PM UTC) on weekdays only
            Description: Trigger exit trades evaluation at 9:45 AM EST on market days
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /exit-trades
            Method: post
            Description: Manual trigger for exit trades evaluation

  InitiateExitTradesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Environment}-initiate-exit-trades-lambda'
      RetentionInDays: 30

  AlpacaCredentialsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref AlpacaSecretName
      Description: Alpaca trading API credentials
      SecretString: !Sub |
        {
          "keyId": "YOUR_ALPACA_KEY_ID",
          "secretKey": "YOUR_ALPACA_SECRET_KEY",
          "baseUrl": "https://paper-api.alpaca.markets"
        }
      GenerateSecretString:
        ExcludeCharacters: '"@/\'

Outputs:
  InitiateExitTradesLambdaFunctionArn:
    Description: ARN of the Initiate Exit Trades Lambda function
    Value: !GetAtt InitiateExitTradesLambdaFunction.Arn
    Export:
      Name: !Sub '${Environment}-InitiateExitTradesLambdaArn'
  
  InitiateExitTradesLambdaFunctionName:
    Description: Name of the Initiate Exit Trades Lambda function
    Value: !Ref InitiateExitTradesLambdaFunction
    Export:
      Name: !Sub '${Environment}-InitiateExitTradesLambdaName'
  
  ApiGatewayEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/exit-trades'
    Export:
      Name: !Sub '${Environment}-InitiateExitTradesApiEndpoint'

